### ISSUE TITLE
Add ability to set wordWrap: break-word to always wrap newlines at arbitrary break points

### ISSUE THREAD

**Issue by jennifer-shehane** [cli-table/cli-table3#125]
I essentially want the same functionality as css' `overflow-wrap: break-word;`

**Note** `wordWrap: true` does nothing here because there are no `\n` chars in my string.

**My current table code:**

```js
const Table = require('cli-table3')

let table = new Table({
  'colWidths': [3, 36],
})

table.push([
  '✔',
  'stdout_specfile_display_spec_with_a_really_long_name_that_never_has_a_line_break_or_new_line.js',
])


console.log(table.toString())
```

**Console output**

<img width="354" alt="Screen Shot 2019-09-13 at 5 45 16 PM" src="https://user-images.githubusercontent.com/1271364/64896551-45e5ec00-d64e-11e9-8002-e06a04f80e85.png">

I want to pass some option like: `wordWrap: 'break-word` to the TableOptions and/or CellOptions so that I get this output from the code above

**WHAT I WANT OUTPUT**

<img width="355" alt="Screen Shot 2019-09-13 at 5 48 49 PM" src="https://user-images.githubusercontent.com/1271364/64896699-c3116100-d64e-11e9-8b0c-c53f2837e162.png">

Can I do this myself? Yes. Is it a PITA? Yes. 😞

Finding the points to insert newlines would be more convenient from within this library since it already is calculating how to wrapWords and knows the width of the columns/rows already.

**Comment by speedytwenty** [comment]
I took a stab at this with #217.

With the proposed "wrapWord" option, the following code:

```
const Table = require('cli-table3');
let table = new Table({
  colWidths: [3, 36],
  wordWrap: true,
  wrapWords: true, // <- NEW
});

table.push([
  '✔',
  'stdout_specfile_display_spec_with_a_really_long_name_that_never_has_a_line_break_or_new_line.js',
]);
table.push([
  '✔',
  'X stdout_specfile_display_spec_with_a_really_long_name_that_never_has_a_line_break_or_new_line.js XX',
]);
console.log(table.toString());
```

### Produces:

```
┌───┬────────────────────────────────────┐
│ ✔ │ stdout_specfile_display_spec_with_ │
│   │ a_really_long_name_that_never_has_ │
│   │ a_line_break_or_new_line.js        │
├───┼────────────────────────────────────┤
│ ✔ │ X stdout_specfile_display_spec_wit │
│   │ h_a_really_long_name_that_never_ha │
│   │ s_a_line_break_or_new_line.js XX   │
└───┴────────────────────────────────────┘
```
