### ISSUE TITLE
Additional row added when using `rowSpan`

### ISSUE THREAD

**Issue by krasimir** [cli-table/cli-table3#128]
Hello,

my initialization code:

```js
const statesTable = new Table({
  head: ['ID', 'value', 'effects', 'Qs', 'Q result'],
  colWidths: [6, 19, 10, 10, 19]
});
```

here're my rows:

```
[
  [
    {
      "rowSpan": 2,
      "content": "s_1"
    },
    {
      "rowSpan": 2,
      "content": "\"foo\""
    },
    "e_25",
    "map\nmap*\nmutate",
    "\"foo\""
  ],
  [
    "e_26",
    "map\npipe*",
    "\"foo\""
  ]
]
```
And the result is:
![image](https://user-images.githubusercontent.com/528677/65480264-85f06e80-de99-11e9-8068-17e70985fc28.png)

So, I'm wondering if I'm missing something. It looks like the empty cell on the second row shouldn't be there.

**Comment by speedytwenty** [comment]
After solving a similar issue for my own use case, I decided to test it for your use case. The test was successful so it was apparently the same error. #187 resolves this issue.

![image](https://user-images.githubusercontent.com/260874/96679114-490ed980-1330-11eb-8b1e-6e5f66b3b799.png)
