### ISSUE TITLE
Node engine versions missing v11

### ISSUE THREAD

**Issue by stami** [cli-table/cli-table3#176]
> error cli-table3@0.6.0: The engine "node" is incompatible with this module. Expected version "10.* || >= 12.*". Got "11.13.0"

The node version requirements is skipping v11. Is that on purpose? Does this not work on node 11.x or is there a bug in the requirement definitions?
https://github.com/cli-table/cli-table3/blob/master/package.json#L62

I see it has been changed in this commit https://github.com/cli-table/cli-table3/commit/aca5c8c254c0f01438177556c404ae686c121b02

**Comment by Turbo87** [comment]
yes, it is on purpose, because Node v11 is not an LTS release (like all of the odd major version releases of Node.js). as you can see on https://nodejs.org/en/about/releases/ it is no longer officially supported.

**Comment by stami** [comment]
Oh, I see. Thanks for a quick response!
Ended up updating to the latest LTS version on our CI.
