### ISSUE TITLE
Output contains strange character

### ISSUE THREAD

**Issue by tonyxiao** [cli-table/cli-table3#181]
![image](https://user-images.githubusercontent.com/696842/92068030-61ef1a00-edd8-11ea-983f-c669890457c8.png)

This is on macOS with iterm2. Not sure if that's relevant.

**Comment by DanielRuf** [comment]
Please provide a reproducible test case as code so we can test this.

**Comment by speedytwenty** [comment]
Closing this issue as there is not enough info to reproduce it. Please reopen if you can provide a test case or example code that can be used to reproduce the issue.
