### ISSUE TITLE
Looks like node 4 and 5 don't work

### ISSUE THREAD

**Issue by schalkneethling** [cli-table/cli-table3#19]
Opened a PR on json2csv and got the following error report from the maintainer:
https://github.com/zemirco/json2csv/pull/302

> Looks like node 4 and 5 don't work due to Block-scoped declarations (let, const, function, class) not yet supported outside strict mode.
>
> Also color shows up in Node 8 and 9 but not in 6 and 7. We are testing against the > output without the colors, so tests fail in 8 and 9.

https://github.com/zemirco/json2csv/pull/302#issuecomment-396256964

**Comment by Turbo87** [comment]
Node 4 and 5 are EOL and no longer supported by Node themselves, so I set the minimum support for v0.5.0 to Node 6+

**Comment by schalkneethling** [comment]
@Turbo87 Yup, I was thinking we need to define those things. How do we handle situations where the lib depending on cli-table still need to support those versions? Do we just inform them that there is a security vulnerability and that cli-table3 only support 6+? Do we close the PR or let them close the PR?

**Comment by Turbo87** [comment]
cli-table3@0.4.0 was targetting Node 0.10/0.11, so they can use that one if they want.

**Comment by Turbo87** [comment]
Node version requirements are defined by https://github.com/cli-table/cli-table3/blob/v0.5.0/package.json#L60

**Comment by DanielRuf** [comment]
Node.js 4 and 5 are EOL.
