### ISSUE TITLE
Set width of table based on terminal width

### ISSUE THREAD

**Issue by talkncloud** [cli-table/cli-table3#191]
Hi,

Is it possible to have a dynamic width table based on the width of the terminal? I see that column widths are optional but this doesn't format the table as expected as pushes data outside of the bounds and setting a column width with a terminal that is too small pushes the data out of bounds:

Column width unset:
![image](https://user-images.githubusercontent.com/72372757/99721575-2cb2b800-2afb-11eb-9020-280003a47b1f.png)

Column width set:
![image](https://user-images.githubusercontent.com/72372757/99721662-4653ff80-2afb-11eb-955d-a42a50b70bb1.png)

Now if i set the column width but make the terminal smaller than the total width:
![image](https://user-images.githubusercontent.com/72372757/99721765-671c5500-2afb-11eb-9fcb-f866f3655c2a.png)

Thank you.

**Comment by slavafomin** [comment]
This is indeed a very needed feature.

**Comment by speedytwenty** [comment]
Just contemplating on how this might be accomplished. While I don't think detecting the terminal width would be in scope here, I could imagine this detection being done externally. So getting that exactly right would be on the implementor, but if the table API supported something like this:

```
const myTable = new Table({
  head: ['group', 'service', 'description', 'price'],
  width: process.stdout.columns || 400,
  colWidths: [100, 'fluid', 100, 100],
});
```
There would be some implications to consider in the API to support multiple "fluid" columns. If you could specify a column as fluid and additional specific a "minimum" width, I think that'd cover a lot of desired use cases.

I'd say the task or specific request is "Allow fixed width table with fluid column widths".

**Comment by speedytwenty** [comment]
Now that I post the code, I see that it is possible to do as it.

Something like might suit what you're looking for:
```
const maxWidth = process.stdout.columns || 400;
const myTable = new Table({
  head: ['group', 'service', 'description', 'price'],
  colWidths: [100, maxWidth - 300, 100, 100],
});
```

**Comment by speedytwenty** [comment]
Haven't done any testing, but this should be accomplishable with the current API (as described in my previous comment).
