### ISSUE TITLE
Add TypeScript type definitions

### ISSUE THREAD

**Issue by DanielRuf** [cli-table/cli-table3#20]
https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by Turbo87** [comment]
Yeah, I think that would be useful, although I'm tempted to just port the project to use TypeScript directly instead... 🤔

**Comment by DanielRuf** [comment]
Unfortunaltey this does not seem to work with some tools like tslint which looks for `@types/cli-table3`. So we have to create this to satisfy the tools.

**Comment by Turbo87** [comment]
@DanielRuf I'm very surprised by that. This is the official and documented way to provide type declarations for TypeScript. Do you have a reproduction somewhere where this does not work and creates problems?

**Comment by DanielRuf** [comment]
@Turbo87 yes, try `npm i` with https://github.com/ashblue/uvpm-cli/pull/10

**Comment by Turbo87** [comment]
@DanielRuf 0.5.0 does not include the type definitions yet. apparently I forgot to release it 🤦‍♂️

**Comment by Turbo87** [comment]
@DanielRuf I've published v0.5.1 including the typedefs, so this should work fine now
