### ISSUE TITLE
Travis build suspended? 

### ISSUE THREAD

**Issue by speedytwenty** [cli-table/cli-table3#271]
The tests are presently failing and there is no indication of this with this in build-status badge. The last build was 6 months ago and there is no build for commits to master since then.

https://app.travis-ci.com/github/cli-table/cli-table3/branches

While I'm logged into TravisCI, it says:

```Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the [Plan page](https://app.travis-ci.com/organizations/cli-table/plan) to replenish your credit balance or alter your [Consume paid credits for OSS setting](https://app.travis-ci.com/organizations/cli-table/plan?anchor=oss-consumption).```

Not sure who specifically has access to see what's going on with Travis, but it will be ideal to get this resolved so that it is apparent when the build fails (as it would presently).

**Comment by DanielRuf** [comment]
Relevant news with the new OSS (10k) credit: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by speedytwenty** [comment]
I don't really have a preference beyond the desire of being prevented from accidentally releasing a failing build.

It looks like Travis was configured to build on Node 10, 12, and 13. I suppose it would be ideal to reestablish that by whatever means may be best—and least likely to be impeded by outages/suspensions in the future. Not too familiar with GHA and not familiar with the options available for running the builds. I can poke around but if anyone knows of a current example that'd be helpful! 

Additionally, it might be worth considering a pre-commit hook that runs eslint and the tests to help ensure contributors are submitting tested code. While I don't prefer the added dependency [for dev], something like [Husky](https://www.npmjs.com/package/husky) would promote tested code without the dependency of a 3rd-party service.

**Comment by speedytwenty** [comment]
I've got an attempt of GHA in progress here: https://github.com/speedytwenty/cli-table3/pull/8

I'll get a PR in here once I've got it sufficiently working.

**Comment by speedytwenty** [comment]
Going to go ahead and merge this as I have a few other PRs in and more on the way.
