### ISSUE TITLE
chore: migration from cli-table2 to cli-table3

### ISSUE THREAD

**Issue by DanielRuf** [cli-table/cli-table3#28]
Current list:

- [ ] [`@allstar/allstar-cli`](https://www.npmjs.com/package/@allstar/allstar-cli)
- [ ] [`@builtioflow/connector-builder`](https://www.npmjs.com/package/@builtioflow/connector-builder)
- [ ] [`@dasnoo/arsocket-server`](https://www.npmjs.com/package/@dasnoo/arsocket-server)
- [ ] [`@datapull/cli`](https://www.npmjs.com/package/@datapull/cli)
- [x] [`@jaycenhorton/eth-gas-reporter`](https://www.npmjs.com/package/@jaycenhorton/eth-gas-reporter)
- [ ] [`@koale/clichords`](https://www.npmjs.com/package/@koale/clichords)
- [ ] [`@mozheng-neal/github_cli`](https://www.npmjs.com/package/@mozheng-neal/github_cli)
- [ ] [`@practo/rev-replace-plugin`](https://www.npmjs.com/package/@practo/rev-replace-plugin)
- [ ] [`@secapps/cohesion`](https://www.npmjs.com/package/@secapps/cohesion)
- [ ] [`@simplrjs/azure-storage-backup`](https://www.npmjs.com/package/@simplrjs/azure-storage-backup)
- [ ] [`@sinchang/12306cli`](https://www.npmjs.com/package/@sinchang/12306cli)
- [ ] [`@sleepez/shopkeeper`](https://www.npmjs.com/package/@sleepez/shopkeeper)
- [ ] [`@synctree/libijs`](https://www.npmjs.com/package/@synctree/libijs)
- [ ] [`@zf/jenkins-cli`](https://www.npmjs.com/package/@zf/jenkins-cli)
- [ ] [`airlane-hangar-cli`](https://www.npmjs.com/package/airlane-hangar-cli)
- [ ] [`alive-push-cli`](https://www.npmjs.com/package/alive-push-cli)
- [ ] [`alphi`](https://www.npmjs.com/package/alphi)
- [ ] [`anypoint-cli`](https://www.npmjs.com/package/anypoint-cli)
- [ ] [`apigee-edge-cli`](https://www.npmjs.com/package/apigee-edge-cli)
- [ ] [`augmentable-cli`](https://www.npmjs.com/package/augmentable-cli)
- [ ] [`aws-env-manager`](https://www.npmjs.com/package/aws-env-manager)
- [ ] [`banana-log`](https://www.npmjs.com/package/banana-log)
- [ ] [`baresoil-provider-aws`](https://www.npmjs.com/package/baresoil-provider-aws)
- [ ] [`baresoil`](https://www.npmjs.com/package/baresoil)
- [ ] [`basta`](https://www.npmjs.com/package/basta)
- [ ] [`blocxus-test`](https://www.npmjs.com/package/blocxus-test)
- [ ] [`cee`](https://www.npmjs.com/package/cee)
- [ ] [`chrome-cli-win`](https://www.npmjs.com/package/chrome-cli-win)
- [ ] [`cli-catarinense`](https://www.npmjs.com/package/cli-catarinense)
- [ ] [`cloudhub-cli`](https://www.npmjs.com/package/cloudhub-cli)
- [ ] [`cmis-env-spa`](https://www.npmjs.com/package/cmis-env-spa)
- [ ] [`cmis-package-server`](https://www.npmjs.com/package/cmis-package-server)
- [ ] [`coinrush`](https://www.npmjs.com/package/coinrush)
- [ ] [`cointracker`](https://www.npmjs.com/package/cointracker)
- [ ] [`crypto-coins`](https://www.npmjs.com/package/crypto-coins)
- [ ] [`diabot`](https://www.npmjs.com/package/diabot)
- [ ] [`disclosure`](https://www.npmjs.com/package/disclosure)
- [ ] [`doc-md-import`](https://www.npmjs.com/package/doc-md-import)
- [ ] [`easytimes`](https://www.npmjs.com/package/easytimes)
- [ ] [`embed-support`](https://www.npmjs.com/package/embed-support)
- [ ] [`flowdock-deploy-notify`](https://www.npmjs.com/package/flowdock-deploy-notify)
- [ ] [`football-cli`](https://www.npmjs.com/package/football-cli)
- [ ] [`fp-cli`](https://www.npmjs.com/package/fp-cli)
- [ ] [`gauge-cli`](https://www.npmjs.com/package/gauge-cli)
- [ ] [`grid-cli`](https://www.npmjs.com/package/grid-cli)
- [ ] [`hsskgv`](https://www.npmjs.com/package/hsskgv)
- [ ] [`hubert`](https://www.npmjs.com/package/hubert)
- [ ] [`install-missing-require`](https://www.npmjs.com/package/install-missing-require)
- [ ] [`installer-bench`](https://www.npmjs.com/package/installer-bench)
- [ ] [`json2csv-plus`](https://www.npmjs.com/package/json2csv-plus)
- [ ] [`juejin`](https://www.npmjs.com/package/juejin)
- [ ] [`license-checker-cli`](https://www.npmjs.com/package/license-checker-cli)
- [ ] [`litter-translator`](https://www.npmjs.com/package/litter-translator)
- [ ] [`loadmark`](https://www.npmjs.com/package/loadmark)
- [ ] [`med-rn-cli`](https://www.npmjs.com/package/med-rn-cli)
- [ ] [`mykurisu-cli`](https://www.npmjs.com/package/mykurisu-cli)
- [ ] [`nano-scripts`](https://www.npmjs.com/package/nano-scripts)
- [ ] [`node-gitstar`](https://www.npmjs.com/package/node-gitstar)
- [ ] [`node-qi`](https://www.npmjs.com/package/node-qi)
- [ ] [`pada`](https://www.npmjs.com/package/pada)
- [ ] [`panda-bin`](https://www.npmjs.com/package/panda-bin)
- [ ] [`pm2-jhonny`](https://www.npmjs.com/package/pm2-jhonny)
- [ ] [`pm25-go`](https://www.npmjs.com/package/pm25-go)
- [ ] [`quixxi-cli`](https://www.npmjs.com/package/quixxi-cli)
- [ ] [`quran-cli2`](https://www.npmjs.com/package/quran-cli2)
- [ ] [`qusandboxcli`](https://www.npmjs.com/package/qusandboxcli)
- [ ] [`qxf2006hf0216`](https://www.npmjs.com/package/qxf2006hf0216)
- [ ] [`r8s-cli`](https://www.npmjs.com/package/r8s-cli)
- [ ] [`redcore-miniapp-cli`](https://www.npmjs.com/package/redcore-miniapp-cli) [Not on Github]
- [ ] [`scaleway-cmd`](https://www.npmjs.com/package/scaleway-cmd)
- [ ] [`self-easy-template-cli`](https://www.npmjs.com/package/self-easy-template-cli)
- [x] [`servicebus-trace`](https://www.npmjs.com/package/servicebus-trace) [issue#52](https://github.com/cli-table/cli-table3/issues/52)
- [x] [`skgq`](https://www.npmjs.com/package/skgq)
- [x] [`skgradver`](https://www.npmjs.com/package/skgradver)
- [x] [`skgv`](https://www.npmjs.com/package/skgv)
- [x] [`sonarish-plugin-eslint-ruleset`](https://www.npmjs.com/package/sonarish-plugin-eslint-ruleset)
- [ ] [`ssh-host-manager`](https://www.npmjs.com/package/ssh-host-manager) [issue#51](https://github.com/cli-table/cli-table3/issues/51)
- [x] [`syncano-cli`](https://www.npmjs.com/package/syncano-cli)
- [x] [`time-tracker-cli`](https://www.npmjs.com/package/time-tracker-cli)
- [x] [`timesheet-cli`](https://www.npmjs.com/package/timesheet-cli)
- [x] [`tntvillage`](https://www.npmjs.com/package/tntvillage)
- [x] [`togen`](https://www.npmjs.com/package/togen)
- [x] [`toolbot-core-experiment`](https://www.npmjs.com/package/toolbot-core-experiment)
- [x] [`translate-hexon`](https://www.npmjs.com/package/translate-hexon)
- [x] [`travelchain-beta-ui`](https://www.npmjs.com/package/travelchain-beta-ui)
- [x] [`vtex`](https://www.npmjs.com/package/vtex)
- [x] [`wm-check-blocks`](https://www.npmjs.com/package/wm-check-blocks)
- [x] [`yzz-node-query`](https://www.npmjs.com/package/yzz-node-query)

**Comment by DanielRuf** [comment]
Updated the list. I have created PRs for all repos where I directly found the GitHub repository.

The rest has to be checked (again).

And we still need `@types/cli-table3` for some PRs.

**Comment by schalkneethling** [comment]
@DanielRuf @Turbo87 should we open this up to folks that want to contribute during hacktoberfest? Seems like really neat good first bugs.

We might need to split this out to individual issues where we know the change still needs to be made and the repo actually still exists.

Let me know your thoughts. Thanks!

**Comment by DanielRuf** [comment]
So far almost all repos should have a PR for the migration but there might be new projects using cli-table2. So yes, it makes sense to see if contributors want to help migrating projects as part of Hacktoberfest.

**Comment by schalkneethling** [comment]
Thanks @DanielRuf, I will go over the list above and see where help is still needed. For those that I can identify, I will create individual issues and mark them as `good-first-bug` as well as `hacktoberfest`

**Comment by Turbo87** [comment]
closing this issue, since it's not an issue with our repo, but with the individual repos. we can still keep this list updated when we migrate repos, but it doesn't need to be an open issue IMHO.

**Comment by DanielRuf** [comment]
Afaik I have created issues in (almost) all listed repos so we can close here.
