### ISSUE TITLE
Short term roadmap/contributor access

### ISSUE THREAD

**Issue by speedytwenty** [cli-table/cli-table3#293]
**I'm seeking access [and any inapparent special instructions] to publish [npm] releases for cli-table3.** @Turbo87 @DanielRuf 

**The short term roadmap is a bug-fix and feature additions release: `v0.6.2`. Followed later by a `v0.6.3` release which hones in on performance—both speed and memory consumption—without breaking the API****. I'm not sure where Typescript support stands but I aim to know before v0.6.3 (#295).

--------

I've spent the last ~10 days methodically picking a couple years worth of _low-hanging-fruit_ as well as getting pretty intimate with this entire package; including source, tests, dependencies, documentation, and documentation generation.

If granted, I will seek to automate and document the release process for ourselves and future contributors to include any of the following that may not already be present:

- Ensure tests (which include linting) are passing before release
- Ensure docs are generated and unchanged or included in release
- CHANGELOG.md is updated via lerna-changelog
- version in package.json is bumped appropriately

-------

### v0.6.2

This will be a release of the latest fixes and feature additions—before further refactoring. Including:

* Rendering time reduced by 1/3 for large tables (100k cells render in 20 seconds instead of 120 seconds)
* [Layout rendering nearly impenetrable](https://github.com/cli-table/cli-table3/blob/8b2fbabdb6cf77b17a117ff790f0f684e2d2f67f/test/table-test.js#L105) (bug fix + awesome)!
* Links are now supported! (#292)
* _Alternative_ word wrap! (#217)
* Rudimentary debugging capabilities (#288)
* Random table generation/performance testing script (#294) _for performance comparisons with the following version (see below)_

-------

### v0.6.3
_potentially v0.7.0_

**Performance knockout!**
This will reduce the rending time of cli-table3 by _~3,600%_ and memory usage will be minimized **without breaking the API**.

**Custom cells**
Cell will be heavily refactored and the API sanitized. Not sure how well it will be documented, but it will be possible to populate tables with custom cells that extend the [refactored] Cell.

**There may be "deep" API breakage in v0.6.3 for anyone that uses cli-table3's internal classes or functions.

**Comment by speedytwenty** [comment]
Noting, that I'm anticipating a breaking `v0.7.0` release with #295. To continue supporting Node version 13.x is likely more hassle than it's worth. It could be avoided, but it probably makes sense to drop support for Node 13 to avoid dependency issues.

**Comment by Turbo87** [comment]
👋 @speedytwenty 

sorry, I was on vacation. I just gave you publish permission on npm. thanks a lot for your work on this package! :)
