### ISSUE TITLE
@0xcda7a/npm status

### ISSUE THREAD

**Issue by schalkneethling** [cli-table/cli-table3#31]
On of the packages that depends on `cli-table` is https://www.npmjs.com/package/@0xcda7a/npm

Not sure what to make of it. It is not the canonical `npm` package so, not sure we should be doing anything about it. Thoughts? @Turbo87 @DanielRuf

**Comment by DanielRuf** [comment]
I guess this is just a test package by someone. There are more like this where they cloned npm and republished it.

**Comment by schalkneethling** [comment]
Ok, going to tick that one of the list and close this issue. Thanks @DanielRuf
