### ISSUE TITLE
wordWrap still trims messages

### ISSUE THREAD

**Issue by TranVanDung-Leo** [cli-table/cli-table3#315]
When I show error.stack of an Error
   Example: Error("This article shows how to fetch GraphQL data in React with the useQuery hook and attach the result to your UI. You'll also learn how Apollo Client simplifies data management code by tracking error and loading states for you. { data: This article shows how to fetch GraphQL data in React with the useQuery hook and attach the result to your UI. You'll also learn how Apollo Client \n simplifies data management code by tracking error and loading states for you, data2: This article shows how to fetch GraphQL data in React with the useQuery hook and attach the result to your UI. You'll also learn how Apollo Client simplifies data management code by tracking error and loading states for you}");

![image](https://user-images.githubusercontent.com/115515422/209144252-e735ab08-2ff2-4e76-8cb5-24b0cc9644df.png)

**Comment by speedytwenty** [comment]
Please provide the code that produces the table with this behavior for attempting to reproduce your issue.

**Comment by TranVanDung-Leo** [comment]
`
try {
  throw new Error("This article shows how to fetch GraphQL data in React with the useQuery hook and attach the result to your UI. You'll also learn how Apollo Client simplifies data management code by tracking error and loading states for you. { data: This article shows how to fetch GraphQL data in React with the useQuery hook and attach the result to your UI. You'll also learn how Apollo Client \n simplifies data management code by tracking error and loading states for you, data2: This article shows how to fetch GraphQL data in React with the useQuery hook and attach the result to your UI. You'll also learn how Apollo Client simplifies data management code by tracking error and loading states for you}");
} catch (error) {
   var table = new Table({
      head: [String(error)],
      colWidths: [74],
      wordWrap: true,
    });
   table.push([
      error.stack
        .split(/\n+/)
        .map((line) => line.trim())
        .filter((line) => line.startsWith("at "))
        .join("\n"),
    ]);
    console.log(table.toString());
}
`

**Comment by speedytwenty** [comment]
"Words" (non-space delimited strings)  that exceed your column width are being truncated instead of wrapped.

Try adding the option `wrapOnWordBoundary: false` to your table options.

This option is described [here](https://github.com/cli-table/cli-table3/blob/master/basic-usage.md#using-wordwrap-set-wraponwordboundary-to-false-to-ignore-word-boundaries).

Eg.
```js
  var table = new Table({
      head: [String(error)],
      colWidths: [74],
      wordWrap: true,
      wrapOnWordBoundary: false,
   });
```
