### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by hashfi-motion** [cli-table/cli-table3#329]
```
Error [ERR_REQUIRE_ESM]: require() of ES Module D:..\node_modules\string-width\index.js from D:\...\node_modules\cli-table3\src\utils.js not supported.
Instead change the require of index.js in D:\...\node_modules\cli-table3\src\utils.js to a dynamic import() which is available in all CommonJS modules.
```

My project is in TypeScript, this is the error I got when I try to run it.
Let me know if you need more information.

**Comment by hashfi-motion** [comment]
Never mind, fixed it.
I need to `yarn` in `D:\...\node_modules\cli-table3` first

**Comment by RobinClowers** [comment]
I'm also seeing this error, and I don't understand the fix you posted, are you saying you had to `cd` into `node_modules\cli-table3` and run `yarn install`? If so there is something very wrong!

**Comment by speedytwenty** [comment]
Please see [my relevant comment](https://github.com/cli-table/cli-table3/issues/330#issuecomment-1780110699) in #330
