### ISSUE TITLE
Update @bigboat/cli

### ISSUE THREAD

**Issue by schalkneethling** [cli-table/cli-table3#33]
Created pull request to update to cli-table3:
https://github.com/bigboat-io/cli/pull/1

**Comment by Turbo87** [comment]
@schalkneethling I don't think we need to open issues here for every single update PR. this creates a lot of unnecessary notifications.

**Comment by schalkneethling** [comment]
@Tur	I was not sure how we can prevent double work so, this was an attempt at that :p I do understand that it will lead to noise. Any other suggestions?

The main problem I think is that the list is so big, Github has problems dealing with it. Perhaps we can comment in the main thread? Although that probably will not help at all :(
