### ISSUE TITLE
stringWidth Error

### ISSUE THREAD

**Issue by Vercjames** [cli-table/cli-table3#330]
Issue when trying to install and use cil-table3

require() of ES Module /node_modules/string-width/index.js from node_modules/cli-table3/src/utils.js not supported.

**Comment by drush** [comment]
Same issue.  

Stack: vite, typescript, react

storybook 7.3.0

**Comment by RakeshPotnuru** [comment]
@drush @james-arawhanui @Vercjames 
Check out [this](https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092) conversation on storybook.

**Comment by joeprivettsmart** [comment]
Same problem here. We are assuming that `clitable-3` needs to update `src/utils.js` to import `string-width` rather than use `require`.

**Comment by speedytwenty** [comment]
There hasn't been a change to cli-table3 to introduce this issue so it's unclear where/why this is occurring.

cli-table3 defines it's dependency on `string-width` as `^4.2.0`. Version 4.x is not an ESM.

It seems like somehow a version of `string-width` that is version 5+ is getting installed.

Converting cli-table3 to a module would be a breaking change that I don't have time for presently.

I'm only vaguely familiar with storybook, so information on how this issue can be reproduced more basically would help me find a resolution.

**Comment by speedytwenty** [comment]
> @drush @james-arawhanui @Vercjames Check out [this](https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092) conversation on storybook.

Based on this discussion, this issue appears to be related with yarn version 1 and not directly related to cli-table3—which confirms my hunch that an incorrect version of `string-width` is getting installed/linked.

Please review [the conversation on storybook](https://github.com/storybookjs/storybook/issues/22431#issuecomment-1630086092) and if the issue persists—reopen this issue with instructions on how to reproduce without storybook.

**Comment by wajahat9876** [comment]
"After upgrading my Expo project from SDK 51 to SDK 52, I encountered a TypeError: stringWidth is not a function. I resolved the issue by removing node_modules and yarn.lock, clearing the Yarn cache, and then reinstalling dependencies using yarn install."
rm -rf node_modules
rm yarn.lock
yarn cache clean
yarn install
