### ISSUE TITLE
Merge with tty-table

### ISSUE THREAD

**Issue by tecfu** [cli-table/cli-table3#36]
HI guys, 

I'm quite curious about this project, because I've been maintaining a backwards compatible alternative to [cli-table](github.com/automattic/cli-table) that has possibly resolved some of the issues that would have caused you to fork its fork: [cli-table2](https://github.com/jamestalmage/cli-table2). 

I see this chain of forks (cli-table/cli-table2/cli-table3) as a humorous, but sad microcosm of open source on Github. Feel free to cherry pick any of my source to apply it towards cli-table3, or perhaps you could create a tty-table2, tty-table3, etc like you have with cli-table here. 

Also, headhunting the dependents of your parent forks via PR is a novel move. Nice.

**Comment by Turbo87** [comment]
Our main issue with cli-table2 was that there were changes on the master branch that had not been released for years and the maintainer was unresponsive. I don't see any reason to do anything like that for tty-table, not sure why you'd suggest that.

Last time I looked tty-table was also released under the GPL, which is problematic for some people. I noticed that you changed to MIT now. Did you get permission from all your contributors for that license change?

We're always open to PRs if you want to port over some of the functionality :)

**Comment by tecfu** [comment]
>Our main issue with cli-table2 was that there were changes on the master branch that had not been released for years and the maintainer was unresponsive. I don't see any reason to do anything like that for tty-table, not sure why you'd suggest that.

Let me be blunt. I think it was in extremely poor taste to go out an issue PR's en masse to the dependents of cli-table and cli-table2 after you simply cloned cli-table2, and then updated its packages and test suite. 

I hope I'm wrong, but I don't see that you guys have contributed **anything** to cli-table3 that deserves this project being more credible than either of those. Maybe once you can delineate some significant bugfixes or feature additions in your README.md you'd look less like you were making an ego grab. 

>Last time I looked tty-table was also released under the GPL, which is problematic for some people. I noticed that you changed to MIT now. Did you get permission from all your contributors for that license change?

I sincerely have a profound gratitude for each of the 4 other contributors on my project who have made at most a single commit, the most of which was 7 lines. 

But avoiding use of my project (tty-table) due a license change from GPL to MIT that took place without the express written consent of each of those contributors certainly wouldn't be done so on the basis of probable litigation. I think the notion that is even an issue of concern is pedantic at best. 

Now if people simply think my code sucks, bam...that's a reason. But licensing issues? Please. 

I hope you guys stick with your fork, and that two years from now you've added some bugfixes, features, and users. In that order. 

Best of luck.

**Comment by Turbo87** [comment]
> I hope I'm wrong, but I don't see that you guys have contributed anything to cli-table3 that deserves this project being more credible than either of those.

https://github.com/jamestalmage/cli-table2/pull/27 aka. fixing the remaining `npm audit` issue for `npm`

btw I'm really sad about the tone that you use here. I don't understand why you would attack us for taking over maintenance of a package where the maintainer obviously doesn't have time anymore. I would have been more than happy to continue maintaining it under the `cli-table2` name, but since the maintainer was (and still is) unresponsive there wasn't really an alternative.
