### ISSUE TITLE
Update to cli-tabe3 for shyim/ssh-host-manager

### ISSUE THREAD

**Issue by schalkneethling** [cli-table/cli-table3#51]
## Steps to complete

* Go to and fork the following repository: https://github.com/shyim/ssh-host-manager
* Once forked, open the project in your editor of choice, and search the project for the string `cli-table2`
* Change all of these references to `cli-table3`, particularly ensuring that the dependency in `package.json is updated to read:

```
"cli-table3": "^0.5.0",
```

* Open a pull request to the original repository
* Add a comment here linking to your PR

You can use the following copy as the title and description of your pull request:

### Title

Updates dependency cli-table2 to cli-table3

### Description

This PR updates the cli-table2 dependency to cli-table3, which fixes one of the npm audit warnings :)

cli-table2 (like cli-table itself) is no longer maintained. In jamestalmage/cli-table2#43 a couple of people have offered to take over maintenance but the current maintainer did not respond so as a result the project was forked to cli-table/cli-table3.

**Comment by TremaineNeethling** [comment]
https://github.com/shyim/ssh-host-manager/pull/1

**Comment by macieklad** [comment]
Hello, I was working in the pararell on this issue, and while I was refactoring the typescript code, I found and error #53, can you take a look ?

**Comment by schalkneethling** [comment]
Thanks @TremaineNeethling 🎉
