### ISSUE TITLE
Update to cli-table3 for mateodelnorte/servicebus-trace

### ISSUE THREAD

**Issue by schalkneethling** [cli-table/cli-table3#52]
## Steps to complete

* Go to and fork the following repository: https://github.com/mateodelnorte/servicebus-trace
* Once forked, open the project in your editor of choice, and search the project for the string `cli-table2`
* Change all of these references to `cli-table3`, particularly ensuring that the dependency in `package.json is updated to read:

```
"cli-table3": "^0.5.0",
```

* Open a pull request to the original repository
* Add a comment here linking to your PR

You can use the following copy as the title and description of your pull request:

### Title

Updates dependency cli-table2 to cli-table3

### Description

This PR updates the cli-table2 dependency to cli-table3, which fixes one of the npm audit warnings :)

cli-table2 (like cli-table itself) is no longer maintained. In jamestalmage/cli-table2#43 a couple of people have offered to take over maintenance but the current maintainer did not respond so as a result the project was forked to cli-table/cli-table3.

**Comment by macieklad** [comment]
Hello, I've started working on the issue, but I encountered a problem with the library in the process #53, can you give it a look first ?

**Comment by macieklad** [comment]
[https://github.com/mateodelnorte/servicebus-trace/pull/1](mateodelnorte/servicebus-trace#1)

**Comment by DanielRuf** [comment]
It's merged 🎉 
So I'm closing this issue here.
