### ISSUE TITLE
Fix the union "Table" type definition

### ISSUE THREAD

**Issue by macieklad** [cli-table/cli-table3#54]
While I was working on the issue #28, after updating the code for the new version of cli-table, typescript threw at me the following error for the push method of the Table type. 

`Cannot invoke an expression whose type lacks a call signature. Type '((...items: Cell[][]) => number) | ((...items: VerticalTableRow[]) => number) | ((...items: CrossTableRow[]) => number)' has no compatible call signatures.`

### The problem

The method was called with proper signature, but it still throws the error.

### The solution

It seems that the "Table" union type definition was created incorrectly, as Typescript prefers to wrap the generics with a single type instead of creating new ones for them.

I created a pull request for the suggested solution #53

**Comment by schalkneethling** [comment]
Thanks @macieklad this has been merged.
