### ISSUE TITLE
Next release: 0.5.1

### ISSUE THREAD

**Issue by DanielRuf** [cli-table/cli-table3#58]
I guess we can publish the next release (should be a patch release or should we bump the minor version?).

https://github.com/cli-table/cli-table3/compare/v0.5.0...master

**Comment by Turbo87** [comment]
see https://github.com/cli-table/cli-table3/pull/53#discussion_r224134157

**Comment by DanielRuf** [comment]
Either we change / keep the type definition or bump cli-table3 to 0.6.0.

Opinions?
